@startuml
skinparam linetype polyline
hide circle
hide stereotype

class "**ChildReport**" as ChildReport {
  |_ subject 1..1   
  |_ lastUpdate 1..1   
  |_ presentedForm 1..1   
  |_ relatedPerson 1..1   
    |_ relationship 1..1   
  |_ pregnancyDetails 0..1   
    |_ durationOfPregnancy 0..1   
      |_ subject 1..1   
      |_ focus 0..1   
      |_ code 1..1   
      |_ valueInteger 1..1   
    |_ pregnancyCMVInfection 0..1   
      |_ subject 1..1   
      |_ focus 0..1   
      |_ code 1..1   
      |_ valueBoolean 1..1   
  |_ bacterialMeningitis 0..1   
    |_ code 1..1   
    |_ subject 1..1   
    |_ valueBoolean 1..1   
  |_ neonatalHearingScreeningLeft 0..1   
    |_ date 1..1   
    |_ subject 1..1   
      |_ code 1..1   
      |_ valueCode 1..1   
  |_ neonatalHearingScreeningRight 0..1   
    |_ date 1..1   
    |_ subject 1..1   
      |_ code 1..1   
      |_ valueCode 1..1   
  |_ severeHeadTrauma 0..1   
    |_ subject 1..1   
    |_ date 1..1   
    |_ code 1..1   
    |_ valueBoolean 1..1   
  |_ eyeScreening 0..*   
    |_ subject 1..1   
    |_ date 1..1   
    |_ code 1..1   
    |_ valueCodeableConcept 1..1   
  |_ eyeResults 0..*   
    |_ inspectionPupilAbnormal 0..1   
      |_ subject 1..1   
      |_ date 1..1   
      |_ code 1..1   
      |_ valueBoolean 1..1   
    |_ eyeMovementAndPosition 0..*   
      |_ subject 1..1   
      |_ date 1..1   
      |_ code 1..1   
      |_ valueCode 1..1   
    |_ eyeRemarks 0..1   
      |_ subject 1..1   
      |_ date 1..1   
      |_ code 1..1   
      |_ valueString 1..1   
  |_ inTreatmentWithOphthalmologist 0..*   
    |_ date 1..1   
    |_ code 1..1   
    |_ valueCode 1..1   
}
@enduml


}
@enduml